apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clouddriver-pod-delete
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cpd
            image: tensaibankai/clouddriver-pod-delete
          restartPolicy: OnFailure